# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f8d09dc927373f219ac9440c92579924"
name = "forever-admin-app"
handle = "forever-admin-app-fp"
application_url = "https://admin.forever-footprints.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "forever-app-development.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_shipping,write_assigned_fulfillment_orders,write_customers,write_merchant_managed_fulfillment_orders,write_orders,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [
  "https://admin.forever-footprints.com/auth/callback",
  "https://admin.forever-footprints.com/auth/shopify/callback",
  "https://admin.forever-footprints.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/app/order_fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
